apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: server
  name: locust-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: server
    spec:
      containers:
          - image: nginx
            name: locust-server
            ports:
              - containerPort: 80
            resources: {}
      restartPolicy: Always
      # Getting set in the benchmark tool
      #nodeSelector:
      #  kubernetes.io/hostname: kind-worker
status: {}


---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: server
  name: locust-server
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: server
status:
  loadBalancer: {}